#!/usr/bin/env python3
"""
fleet-dashboard-generator.py — CCC 🦀

Generate a static HTML dashboard from fleet health check data.
This produces a self-contained HTML file that can be served anywhere
or emailed as a report.

Usage:
    python3 scripts/fleet-health-check.py --json > /tmp/fleet-health.json
    python3 fleet-dashboard-generator.py /tmp/fleet-health.json > dashboard.html
"""

import sys
import json
from datetime import datetime, timezone

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Fleet Dashboard — {timestamp}</title>
<style>
:root {{
  --bg: #0a0a0f;
  --surface: #111118;
  --border: #1e1e2e;
  --text: #e2e8f0;
  --muted: #64748b;
  --accent: #06b6d4;
  --green: #22c55e;
  --yellow: #eab308;
  --red: #ef4444;
}}
body {{
  background: var(--bg);
  color: var(--text);
  font-family: 'Inter', system-ui, sans-serif;
  margin: 0;
  padding: 2rem;
  line-height: 1.6;
}}
.container {{
  max-width: 960px;
  margin: 0 auto;
}}
h1 {{
  font-size: 1.5rem;
  margin: 0 0 0.5rem;
  color: var(--accent);
}}
.timestamp {{
  color: var(--muted);
  font-size: 0.85rem;
  margin-bottom: 1.5rem;
}}
.summary {{
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 1rem;
  margin-bottom: 2rem;
}}
.card {{
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 1.25rem;
  text-align: center;
}}
.card-value {{
  font-size: 2rem;
  font-weight: 700;
  margin: 0.5rem 0;
}}
.card-label {{
  font-size: 0.75rem;
  color: var(--muted);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}}
.service-list {{
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 12px;
  overflow: hidden;
}}
.service-item {{
  display: flex;
  align-items: center;
  padding: 0.85rem 1.25rem;
  border-bottom: 1px solid var(--border);
}}
.service-item:last-child {{
  border-bottom: none;
}}
.service-icon {{
  font-size: 1.25rem;
  margin-right: 1rem;
  width: 28px;
  text-align: center;
}}
.service-info {{
  flex: 1;
}}
.service-name {{
  font-weight: 600;
  font-size: 0.95rem;
}}
.service-url {{
  font-size: 0.75rem;
  color: var(--muted);
  font-family: 'Space Mono', monospace;
}}
.service-status {{
  font-size: 0.75rem;
  font-weight: 700;
  padding: 0.25rem 0.65rem;
  border-radius: 20px;
  text-transform: uppercase;
}}
.status-up {{
  background: rgba(34,197,94,0.15);
  color: var(--green);
}}
.status-down {{
  background: rgba(239,68,68,0.15);
  color: var(--red);
}}
.status-degraded {{
  background: rgba(234,179,8,0.15);
  color: var(--yellow);
}}
.status-timeout {{
  background: rgba(6,182,212,0.15);
  color: var(--accent);
}}
.footer {{
  margin-top: 2rem;
  text-align: center;
  color: var(--muted);
  font-size: 0.8rem;
}}
@media (max-width: 600px) {{
  .summary {{ grid-template-columns: repeat(2, 1fr); }}
  body {{ padding: 1rem; }}
}}
</style>
</head>
<body>
<div class="container">
  <h1>🦀 Fleet Dashboard</h1>
  <div class="timestamp">{timestamp}</div>
  
  <div class="summary">
    <div class="card">
      <div class="card-label">UP</div>
      <div class="card-value" style="color:var(--green)">{up}</div>
    </div>
    <div class="card">
      <div class="card-label">DOWN</div>
      <div class="card-value" style="color:var(--red)">{down}</div>
    </div>
    <div class="card">
      <div class="card-label">DEGRADED</div>
      <div class="card-value" style="color:var(--yellow)">{degraded}</div>
    </div>
    <div class="card">
      <div class="card-label">TIMEOUT</div>
      <div class="card-value" style="color:var(--accent)">{timeout}</div>
    </div>
  </div>
  
  <div class="service-list">
    {services}
  </div>
  
  <div class="footer">
    Generated by CCC 🦀 | Fleet I&O Officer<br>
    Run <code>python3 scripts/fleet-health-check.py --json</code> to update
  </div>
</div>
</body>
</html>
"""

SERVICE_TEMPLATE = """<div class="service-item">
  <div class="service-icon">{icon}</div>
  <div class="service-info">
    <div class="service-name">{name}</div>
    <div class="service-url">{url}</div>
  </div>
  <div class="service-status status-{status_class}">{status}</div>
</div>"""

def generate_dashboard(data):
    up = sum(1 for r in data if r['state'] == 'UP')
    down = sum(1 for r in data if r['state'] == 'DOWN')
    degraded = sum(1 for r in data if r['state'] == 'DEGRADED')
    timeout = sum(1 for r in data if r['state'] == 'TIMEOUT')
    
    services = []
    for r in data:
        icon = {
            'UP': '🟢',
            'DOWN': '🔴',
            'DEGRADED': '🟡',
            'TIMEOUT': '⏱️',
            'ERROR': '❌',
        }.get(r['state'], '❓')
        
        status_class = r['state'].lower()
        
        services.append(SERVICE_TEMPLATE.format(
            icon=icon,
            name=r['name'],
            url=r['url'],
            status=r['state'],
            status_class=status_class,
        ))
    
    return HTML_TEMPLATE.format(
        timestamp=datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC'),
        up=up,
        down=down,
        degraded=degraded,
        timeout=timeout,
        services='\n'.join(services),
    )

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 fleet-dashboard-generator.py <health-check.json>")
        sys.exit(1)
    
    with open(sys.argv[1]) as f:
        data = json.load(f)
    
    print(generate_dashboard(data))

if __name__ == '__main__':
    main()
